version: '3.8'

services:
  forex-app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - SERVER_PORT=8080
      # Must be overriden these values in production
      - EXCHANGE_RATE_API_URL=https://api.exchangerate-api.com/v4
      - EXCHANGE_RATE_API_KEY=22f0770bafaa796bcc150b2e
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s